# Generated by Django 4.1.7 on 2023-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('web', 'web'), ('sumaho', 'Mobile'), ('xr', 'XR'), ('game', 'game'), ('other', 'other')], max_length=100),
        ),
    ]
