# Generated by Django 4.1.7 on 2023-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('web', 'web'), ('mobile', 'mobile'), ('xr', 'XR'), ('game', 'game'), ('other', 'other')], max_length=100),
        ),
    ]
