# Generated by Django 4.2.1 on 2023-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('web', 'web'), ('mobile', 'mobile'), ('xr', 'XR'), ('game', 'game'), ('other', 'other')], max_length=100),
        ),
    ]
